Pin webrick gem
Webrick 1.4.1 was released on the 18th of becember 2017. It requires ruby
>= 2.3.0.

```
Error: /Stage[main]/R10k::Webhook::Package/Package[webrick]/ensure: change
from absent to present failed: Execution of
'/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri webrick'
returned 1: ERROR:  Error installing webrick: webrick requires Ruby
version >= 2.3.0
```